### ISSUE TITLE
Keine Verbindung zu Zusi

### ISSUE THREAD

**Issue by s256** [Basti189/Zusi3Schnittstelle#1]
Moin moin,

großartige Arbeit hier. Darauf habe ich gewartet. Meine Erfahrung mit Arduino ist annähernd 0. Deswegen ist mein Problem vtl. dem geschuldet.

Ich habe dein repo gecloned. EthernetShield als Verbindung eingestellt und die MAC-Adresse geändert. 

Laut Serieller Konsole bekommt der Arduino (Mega, mit EthernetShield) auch eine IP -Adresse. ICMP klappt auch, jedoch erfolgt keine Verbindung zu Zusi 3.

Der TCP-Server von Zusi3 läuft, das sehe ich mittels Netstat direkt, aber auch Telnet oder NC können sich zu dem offenen Zusi3 Socket verbinden.

Stoppe ich den Zusi Server oder ändere ich die IP in eine "ungültige" IP, auf der kein Zusi Server läuft, sehe ich in der seriellen Konsole wie erwartet: ""Verbindung zu Zusi fehlgeschlagen (#)"
>
	zusi = new Zusi3Schnittstelle("192.168.178.106", 1436, "ESP8266Client");
	zusi->setDebugOutput(true);
	//zusi->reqFstAnz(Geschwindigkeit);
	//zusi->reqFstAnz(Status_Zugbeeinflussung);
	//zusi->requestFuehrerstandsbedienung(false);
	//zusi->requestProgrammdaten(false);
	int i = 0;
	while (!zusi->connect()) {
		Serial.print("Verbindung zu Zusi fehlgeschlagen (");
		Serial.print(++i);
		Serial.println(")");
		delay(5000);
	}
	Serial.println("Verbunden mit Zusi");
Auch das auskommentieren von reqFstAnz etc. hat mich nicht weiter gebracht.

Wireshark zeigt mir den Three-Way-Handshake mit anschließendem PSH,ACK in dem der Client-Name inkl. Version übertragen wird (ESP8266Client 0.8.1 beta). Dieser wird ebenfalls mit [ACK] von Zusi bestätigt.

Der Client ist in Zusi auch nicht zu sehen (Konfiguration -> Netzwerk).

Ideen, wo ich hier weiter suchen kann?

Grüße
Se

**Comment by Basti189** [comment]
Das Problem könnte sein, dass dein MEGA zu wenig Arbeitsspeicher hat, da der Verbindungsaufbau ziemlich viel Speicher in Anspruch nimmt. Dies ist der Grund, warum es bei mir mit dem Arduino Uno nicht läuft. In der Zusi3Schnitstelle.cpp Zeile 145 => //delete verbindungsaufbau; //Absturzgrund bei dem ESP32
mal die beiden ersten beiden // rausnehmen, dann gibt er da nämlich wieder etwas Arbeitsspeicher frei, vielleicht reicht das schon, weiß ich aber nicht. Ist jetzt aber alles auch nur eine Vermutung

**Comment by s256** [comment]
Hm hat leider nichts gebracht.
Welchen Arduino nutzt du denn?

**Comment by Basti189** [comment]
Ich nutze dafür den ESP32 oder den ESP8266, siehe auch auf der ersten Seite -> Erfolgreich getestete Boards/Chips

**Comment by s256** [comment]
Ich nochmal, habe nochmal ein wenig geschaut. 

Ich sehe folgende Warnings, wenn ich deinen Code durch Arduino jage?

`sketch/Attribute.cpp: In member function 'byte* Attribute::get()':
sketch/Attribute.cpp:64:37: warning: right shift count >= width of type
  result[2] = (byte)((PACKET_SIZE >> 16) & 0xFF);
sketch/Attribute.cpp:65:37: warning: right shift count >= width of type
  result[3] = (byte)((PACKET_SIZE >> 24) & 0xFF);
sketch/Attribute.cpp: In member function 'int Attribute::getDATAAsInt()':
sketch/Attribute.cpp:108:74: warning: left shift count >= width of type
   return ((DATA[0] & 0xFF) | (DATA[1] & 0xFF) << 8 | (DATA[2] & 0xFF) << 16);
sketch/Attribute.cpp:111:74: warning: left shift count >= width of type
   return ((DATA[0] & 0xFF) | (DATA[1] & 0xFF) << 8 | (DATA[2] & 0xFF) << 16 | (DATA[3] & 0xFF) << 24);
sketch/Attribute.cpp:111:99: warning: left shift count >= width of type
   return ((DATA[0] & 0xFF) | (DATA[1] & 0xFF) << 8 | (DATA[2] & 0xFF) << 16 | (DATA[3] & 0xFF) << 24);
sketch/Zusi3Schnittstelle.cpp: In member function 'Node* Zusi3Schnittstelle::getNodes(byte*)':
sketch/Zusi3Schnittstelle.cpp:298:87: warning: left shift count >= width of type
    int length = ((header[0] & 0xFF) | (header[1] & 0xFF) << 8 | (header[2] & 0xFF) << 16 | (header[3] & 0xFF) << 24); //header[0];
sketch/Zusi3Schnittstelle.cpp:298:114: warning: left shift count >= width of type
    int length = ((header[0] & 0xFF) | (header[1] & 0xFF) << 8 | (header[2] & 0xFF) << 16 | (header[3] & 0xFF) << 24); //header[0];
Sketch uses 25454 bytes (10%) of program storage space. Maximum is 253952 bytes.
Global variables use 1033 bytes (12%) of dynamic memory, leaving 7159 bytes for local variables. Maximum is 8192 bytes.`

Darüber hinaus habe ich nochmal weitergeschaut:

Speicher ist nicht das Problem. 
Das Problem ist der HELLO_ACK. Der kommt nicht.
Ich sehe im Wireshark den Three-Way-Handshake und dann das HELLO als [PSH, ACK]. So weit so richtig.
Jetzt würde ich (nach einem Wireshark Mitschnitt von ZusiDisplay) ein [PSH, ACK] vom ZuSi TCP Server an den Client erwarten (den HELLO_ACK). Der wird aber nicht geschickt. Der Zusi Server quittiert den [PSH, ACK] vom Arduino lediglich mit einem [ACK]. Da stehen natürlich keine Daten drin.

Deshalb ist in der Function Zusi3Schnittstelle::ACK_HELLO() Schluss.

Ich setze ihr Zusi Hobby 3.1.0.0 ein. Setzt du eine andere Version ein?

Oder kommt das über die client->write() Funktion die sich anders Verhält beim Ethernetshield im Vergleich zur WiFi.h zum Beispiel? 

Deinen Code habe ich sonst nicht geändert. Ich arbeite hier nur mit deinem Beispiel Code.
Außer der IP für den Zusi PC natürlich...

**Comment by s256** [comment]
Im TCPDump sehe ich auch den Grund dafür, wieso ich keine Antwort bekomme: Die Länge der Attribute wird falsch geschickt.
Erwartet wäre 40 00 00 00, geschickt wird 40 00 ff 00.
Fehler im Code sehe ich nicht.
Wenn ich in der Attribute.cpp in Zeile 81 (über return..)
`Serial.println((char *)result);`
einfüge, wird die richtige Attribut-Länge geschickt.

Dann steht die Verbindung und ich sehe den Client in Zusi. 
Viel mehr geht dann nicht. 
Alles sehr merkwürdiges Verhalten. 

Ich glaube es ist ein Ressourcen-Problem, mich wundert es nur unheimlich, dass der Code auf meinem Mega nicht läuft, aber auf deinem ESP, der ja deutlich weniger Leistung hat.

**Comment by s256** [comment]
Lesen hilft. ESP32 ist einfach 10-15 mal schneller als der Mega und unterstützt 32bit Operationen.
Kein Wunder dass dein Code auf dem alten Mega nicht läuft :D 
Sorry!
